name: EnvMain workflow

run-name: environment main workflow

on: 
    workflow_dispatch: 

jobs:
    call-workflow:
        uses: ./.github/workflows/EnvReuable.yaml
        with:
            username: Akhil
            purpose: testing workflow call