name: EnvMain workflow

run-name: environment main workflow

on: 
    push:
        branches: 
            - master

jobs:
    call-workflow:
        uses: ./.github/workflows/EnvReuable.yaml
        with:
            username: Akhil
            purpose: testing workflow call