name: test

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      css1: ${{ steps.ak.outputs.name }}
      css2: ${{ steps.ak.outputs.job }}


    steps:
      - name: step1
        id: ak
        run: |
          echo "name=Akhil" >> "$GITHUB_OUTPUT"
          echo "job=devops" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: step2
        run: |
          echo "Name: ${{ needs.job1.outputs.css1 }}"
          echo "job: ${{ needs.job1.outputs.css2 }}"
